# JSON examples and exercise
****
+ get familiar with packages for dealing with JSON
+ study examples with JSON strings and files 
+ work on exercise to be completed and submitted 
****
+ reference: http://pandas.pydata.org/pandas-docs/stable/io.html#io-json-reader
+ data source: http://jsonstudio.com/resources/
****

In [64]:
import pandas as pd
import numpy as np

## imports for Python, Pandas

In [18]:
import json
from pandas.io.json import json_normalize

## JSON example, with string

+ demonstrates creation of normalized dataframes (tables) from nested json string
+ source: http://pandas.pydata.org/pandas-docs/stable/io.html#normalization

In [19]:
# define json string
data = [{'state': 'Florida', 
         'shortname': 'FL',
         'info': {'governor': 'Rick Scott'},
         'counties': [{'name': 'Dade', 'population': 12345},
                      {'name': 'Broward', 'population': 40000},
                      {'name': 'Palm Beach', 'population': 60000}]},
        {'state': 'Ohio',
         'shortname': 'OH',
         'info': {'governor': 'John Kasich'},
         'counties': [{'name': 'Summit', 'population': 1234},
                      {'name': 'Cuyahoga', 'population': 1337}]}]
type(data)

list

In [20]:
# use normalization to create tables from nested element
json_normalize(data, 'counties')

         name  population
0        Dade       12345
1     Broward       40000
2  Palm Beach       60000
3      Summit        1234
4    Cuyahoga        1337

In [21]:
# further populate tables created from nested element
json_normalize(data, 'counties', ['state', 'shortname', ['info', 'governor']])

         name  population    state shortname info.governor
0        Dade       12345  Florida        FL    Rick Scott
1     Broward       40000  Florida        FL    Rick Scott
2  Palm Beach       60000  Florida        FL    Rick Scott
3      Summit        1234     Ohio        OH   John Kasich
4    Cuyahoga        1337     Ohio        OH   John Kasich

****
## JSON example, with file

+ demonstrates reading in a json file as a string and as a table
+ uses small sample file containing data about projects funded by the World Bank 
+ data source: http://jsonstudio.com/resources/

In [51]:
# load json as string
data=pd.read_json('data/world_bank_projects.json')

#data.head()

code  code
11    11      250
10    10      216
8     8       210
2     2       199
6     6       168
4     4       146
7     7       130
5     5        77
9     9        50
1     1        38
3     3        15
Name: code, dtype: int64

In [10]:
# load as Pandas dataframe
sample_json_df = pd.read_json('data/world_bank_projects_less.json')
sample_json_df

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
0,{'$oid': '52b213b38594d8a2be17c780'},1999,November,2013-11-12T00:00:00Z,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,2018-07-07T00:00:00Z,Federal Democratic Republic of Ethiopia!$!ET,ET,Federal Democratic Republic of Ethiopia,Ethiopia,...,"ET,BS,ES,EP",IBRD,Active,N,"{'Name': 'Education for all', 'Percent': 100}","[{'name': 'Education for all', 'code': '65'}]",65,130000000,130000000,http://www.worldbank.org/projects/P129828/ethi...
1,{'$oid': '52b213b38594d8a2be17c781'},2015,November,2013-11-04T00:00:00Z,GOVERNMENT OF TUNISIA,NaN,Republic of Tunisia!$!TN,TN,Republic of Tunisia,Tunisia,...,"BZ,BS",IBRD,Active,N,"{'Name': 'Other economic management', 'Percent...","[{'name': 'Other economic management', 'code':...","54,24",0,4700000,http://www.worldbank.org/projects/P144674?lang=en

****
## JSON exercise

Using data in file 'data/world_bank_projects.json' and the techniques demonstrated above,
1. Find the 10 countries with most projects
2. Find the top 10 major project themes (using column 'mjtheme_namecode')
3. In 2. above you will notice that some entries have only the code and the name is missing. Create a dataframe with the missing names filled in.

In [159]:
#data = pd.read_json('data/world_bank_projects.json') --> returns a DF
with open('data/world_bank_projects.json') as f:
    data = json.load(f)
data[0]

{'sector': [{'Name': 'Primary education'},
  {'Name': 'Secondary education'},
  {'Name': 'Public administration- Other social services'},
  {'Name': 'Tertiary education'}],
 'supplementprojectflg': 'N',
 'projectfinancialtype': 'IDA',
 'prodline': 'PE',
 'mjtheme': ['Human development'],
 'idacommamt': 130000000,
 'impagency': 'MINISTRY OF EDUCATION',
 'project_name': 'Ethiopia General Education Quality Improvement Project II',
 'mjthemecode': '8,11',
 'closingdate': '2018-07-07T00:00:00Z',
 'totalcommamt': 130000000,
 'id': 'P129828',
 'mjsector_namecode': [{'code': 'EX', 'name': 'Education'},
  {'code': 'EX', 'name': 'Education'},
  {'code': 'BX', 'name': 'Public Administration, Law, and Justice'},
  {'code': 'EX', 'name': 'Education'}],
 'docty': 'Project Information Document,Indigenous Peoples Plan,Project Information Document',
 'sector1': {'Percent': 46, 'Name': 'Primary education'},
 'lendinginstr': 'Investment Project Financing',
 'countrycode': 'ET',
 'sector2': {'Percent': 26, 'Name': 'Secondary education'},
 'totalamt': 130000000,
 'mjtheme_namecode': [{'code': '8', 'name': 'Human development'},
  {'code': '11', 'name': ''}],
 'boardapprovaldate': '2013-11-12T00:00:00Z',
 'countryshortname': 'Ethiopia',
 'sector4': {'Percent': 12, 'Name': 'Tertiary education'},
 'prodlinetext': 'IBRD/IDA',
 'productlinetype': 'L',
 'regionname': 'Africa',
 'status': 'Active',
 'country_namecode': 'Federal Democratic Republic of Ethiopia!$!ET',
 'envassesmentcategorycode': 'C',
 'project_abstract': {'cdata': 'The development objective of the Second Phase of General Education Quality Improvement Project for Ethiopia is to improve learning conditions in primary and secondary schools and strengthen institutions at different levels of educational administration. The project has six components. The first component is curriculum, textbooks, assessment, examinations, and inspection. This component will support improvement of learning conditions in grades KG-12 by providing increased access to teaching and learning materials and through improvements to the curriculum by assessing the strengths and weaknesses of the current curriculum. This component has following four sub-components: (i) curriculum reform and implementation; (ii) teaching and learning materials; (iii) assessment and examinations; and (iv) inspection. The second component is teacher development program (TDP). This component will support improvements in learning conditions in both primary and secondary schools by advancing the quality of teaching in general education through: (a) enhancing the training of pre-service teachers in teacher education institutions; and (b) improving the quality of in-service teacher training. This component has following three sub-components: (i) pre-service teacher training; (ii) in-service teacher training; and (iii) licensing and relicensing of teachers and school leaders. The third component is school improvement plan. This component will support the strengthening of school planning in order to improve learning outcomes, and to partly fund the school improvement plans through school grants. It has following two sub-components: (i) school improvement plan; and (ii) school grants. The fourth component is management and capacity building, including education management information systems (EMIS). This component will support management and capacity building aspect of the project. This component has following three sub-components: (i) capacity building for education planning and management; (ii) capacity building for school planning and management; and (iii) EMIS. The fifth component is improving the quality of learning and teaching in secondary schools and universities through the use of information and communications technology (ICT). It has following five sub-components: (i) national policy and institution for ICT in general education; (ii) national ICT infrastructure improvement plan for general education; (iii) develop an integrated monitoring, evaluation, and learning system specifically for the ICT component; (iv) teacher professional development in the use of ICT; and (v) provision of limited number of e-Braille display readers with the possibility to scale up to all secondary education schools based on the successful implementation and usage of the readers. The sixth component is program coordination, monitoring and evaluation, and communication. It will support institutional strengthening by developing capacities in all aspects of program coordination, monitoring and evaluation; a new sub-component on communications will support information sharing for better management and accountability. It has following three sub-components: (i) program coordination; (ii) monitoring and evaluation (M and E); and (iii) communication.'},
 'approvalfy': 1999,
 'projectdocs': [{'DocDate': '28-AUG-2013',
   'EntityID': '090224b081e545fb_1_0',
   'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=090224b081e545fb_1_0',
   'DocType': 'PID',
   'DocTypeDesc': 'Project Information Document (PID),  Vol.'},
  {'DocDate': '01-JUL-2013',
   'EntityID': '000442464_20130920111729',
   'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000442464_20130920111729',
   'DocType': 'IP',
   'DocTypeDesc': 'Indigenous Peoples Plan (IP),  Vol.1 of 1'},
  {'DocDate': '22-NOV-2012',
   'EntityID': '090224b0817b19e2_1_0',
   'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=090224b0817b19e2_1_0',
   'DocType': 'PID',
   'DocTypeDesc': 'Project Information Document (PID),  Vol.'}],
 'lendprojectcost': 550000000,
 'lendinginstrtype': 'IN',
 'theme1': {'Percent': 100, 'Name': 'Education for all'},
 'grantamt': 0,
 'themecode': '65',
 'borrower': 'FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA',
 'sectorcode': 'ET,BS,ES,EP',
 'sector3': {'Percent': 16,
  'Name': 'Public administration- Other social services'},
 'majorsector_percent': [{'Percent': 46, 'Name': 'Education'},
  {'Percent': 26, 'Name': 'Education'},
  {'Percent': 16, 'Name': 'Public Administration, Law, and Justice'},
  {'Percent': 12, 'Name': 'Education'}],
 'board_approval_month': 'November',
 'theme_namecode': [{'code': '65', 'name': 'Education for all'}],
 'countryname': 'Federal Democratic Republic of Ethiopia',
 'url': 'http://www.worldbank.org/projects/P129828/ethiopia-general-education-quality-improvement-project-ii?lang=en',
 'source': 'IBRD',
 'projectstatusdisplay': 'Active',
 'ibrdcommamt': 0,
 'sector_namecode': [{'code': 'EP', 'name': 'Primary education'},
  {'code': 'ES', 'name': 'Secondary education'},
  {'code': 'BS', 'name': 'Public administration- Other social services'},
  {'code': 'ET', 'name': 'Tertiary education'}],
 '_id': {'$oid': '52b213b38594d8a2be17c780'}}

In [161]:
#Answer to Q1
data_norm=json_normalize(data) 
data_norm.head(2)
data_norm.groupby('countryshortname')['_id.$oid'].count().sort_values(ascending=False).head(10)

countryshortname
Indonesia             19
China                 19
Vietnam               17
India                 16
Yemen, Republic of    13
Nepal                 12
Bangladesh            12
Morocco               12
Mozambique            11
Africa                11
Name: _id.$oid, dtype: int64

In [160]:
# Answer to Q2
df_themes = json_normalize(data, 'mjtheme_namecode')
df_themes.groupby('code').name.value_counts().sort_values(ascending=False).head(10)

code  name
11    Environment and natural resources management    223
10    Rural development                               202
8     Human development                               197
2     Public sector governance                        184
6     Social protection and risk management           158
4     Financial and private sector development        130
7     Social dev/gender/inclusion                     119
5     Trade and integration                            72
9     Urban development                                47
1     Economic management                              33
Name: name, dtype: int64

In [154]:
# Answer to Q3
# Create a dictionary with unique theme code and name which will be used to fill 
#in missing names in previous dataframe.
df_themes_unique=df_themes.drop_duplicates(['code','name'])[df_themes.name!=""]
df_themes_unique=df_themes_unique[['code','name']]
df_themes_unique.reset_index(drop=True,inplace=True)
#df_themes_unique
df_themes_unique.set_index('code').sort_index()

/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  after removing the cwd from sys.path.

                                              name
code
1                              Economic management
10                               Rural development
11    Environment and natural resources management
2                         Public sector governance
3                                      Rule of law
4         Financial and private sector development
5                            Trade and integration
6            Social protection and risk management
7                      Social dev/gender/inclusion
8                                Human development
9                                Urban development

In [155]:
from collections import OrderedDict
temp_dict=OrderedDict(df_themes_unique.values.tolist())

In [156]:
#temp_dict={}
#temp_dict=df_themes_unique.to_dict('dict')
df_themes['name']=df_themes['code'].map(temp_dict)
df_themes
#temp_dict

     code                                          name       id
0       8                             Human development  P129828
1      11  Environment and natural resources management  P129828
2       1                           Economic management  P144674
3       6         Social protection and risk management  P144674
4       5                         Trade and integration  P145310
5       2                      Public sector governance  P145310
6      11  Environment and natural resources management  P145310
7       6         Social protection and risk management  P145310
8       7                   Social dev/gender/inclusion  P144665
9       7                   Social dev/gender/inclusion  P144665
10      5                         Trade and integration  P144933
11      4      Financial and private sector development  P144933
12      6         Social protection and risk management  P146161
13      6         Social protection and risk management  P146161
14      2                      Public sector governance  P121185
15      4      Financial and private sector development  P121185
16     11  Environment and natural resources management  P127033
17      8                             Human development  P127033
18     10                             Rural development  P130164
19      7                   Social dev/gender/inclusion  P130164
20      2                      Public sector governance  P130903
21      2                      Public sector governance  P130903
22      2                      Public sector governance  P130903
23     10                             Rural development  P145339
24      2                      Public sector governance  P145339
25     10                             Rural development  P146653
26      6         Social protection and risk management  P146653
27      6         Social protection and risk management  P146653
28     11  Environment and natural resources management  P146653
29      4      Financial and private sector development  P144140
...   ...                                           ...      ...
1469    8                             Human development  P126465
1470    9                             Urban development  P128763
1471    6         Social protection and risk management  P128763
1472    6         Social protection and risk management  P128763
1473    9                             Urban development  P128763
1474    2                      Public sector governance  P131860
1475    2                      Public sector governance  P131860
1476   10                             Rural development  P123322
1477   11  Environment and natural resources management  P123322
1478    8                             Human development  P128096
1479    7                   Social dev/gender/inclusion  P128096
1480   11  Environment and natural resources management  P132138
1481    5                         Trade and integration  P132138
1482    6         Social protection and risk management  P129177
1483    8                             Human development  P129177
1484    4      Financial and private sector development  P127299
1485    7                   Social dev/gender/inclusion  P127299
1486    8                             Human development  P125298
1487    5                         Trade and integration  P125298
1488    2                      Public sector governance  P125298
1489    8                             Human development  P125298
1490   10                             Rural development  P128309
1491    6         Social protection and risk management  P128309
1492   10                             Rural development  P117243
1493   10                             Rural development  P117243
1494   10                             Rural development  P117243
1495    9                             Urban development  P126321
1496    8                             Human development  P126321
1497    5                         Trade and integration  P126321
1498    4      Financial and private sector development  P126321

[1499 rows x 3 columns]